[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "goth-tests"
version = "0.1.1"
description = "Integration tests for yagna"
authors = ["GolemFactory <contact@golem.network>"]
license = "LGPL-3.0-or-later"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
]
repository = "https://github.com/golemfactory/yagna"
documentation = "https://handbook.golem.network"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.3.1"
pytest-asyncio = "^0.21"
pytest-rerunfailures = "^11.1.2"
#goth = "^0.11"
# to use development goth version uncomment below
goth =  { git = "https://github.com/golemfactory/goth.git", rev = "d3617e4acce183e8c878d4c4f9b106222c251494" }

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.782"
poethepoet = "^0.10.0"

[tool.poe.tasks]
codestyle = "black --check --diff ."
goth-assets = "python -m goth create-assets assets"
goth-tests = "pytest -svx . --reruns 0 --only-rerun AssertionError --only-rerun TimeoutError --only-rerun ApiException --only-rerun goth.runner.exceptions.TemporalAssertionError --only-rerun urllib.error.URLError --only-rerun goth.runner.exceptions.CommandError"
provider-tests = "pytest -svx ./domain/ya-provider"
typecheck = "mypy ."
