[package]
name = "ya-utils-networking"
version = "0.2.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[features]
default = ["dns"]
dns = ["anyhow",  "url", "trust-dns-resolver/tokio-openssl"]
vpn = ["ya-relay-stack", "ipnet", "thiserror"]

[dependencies]
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
regex = "1"

#ya-relay-stack = { version = "0.4.1", optional = true }
ya-relay-stack = { git = "https://github.com/golemfactory/ya-relay.git", rev = "f9371b572204365920bbe1f6cc9b3e757bf12887", optional = true }

anyhow = { version = "1.0", optional = true }
trust-dns-resolver = { version = "0.21", optional = true }
url = { version = "2.2", optional = true }

ipnet = { version = "2.3", optional = true }
thiserror = { version = "1.0", optional = true }
